### ISSUE TITLE
Fork roadmap

### ISSUE THREAD

**Issue by qgustavor** [qgustavor/mega#8]
- [x] ~~Fix opened issues~~ one issue to track issue closing, duh...
- [x] Add minified builds
- [ ] Add tests for everything (API requests need to be mocked, maybe using ~~[nock](https://github.com/node-nock/nock)~~ [ava-playback](https://github.com/dempfi/ava-playback))
- [x] Move documentation from readme.md to GitHub ~~Pages~~ *Wiki*
- [x] Create working demos for methods that don't require login
- [ ] Create visual examples of methods that require login (gif animations?)
- [x] Allow global installation allowing something similar to [megatools](https://megatools.megous.com/man/megatools.html): [megajs-cli is being developed](https://github.com/qgustavor/mega-js)
- [ ] Organize branches **(help wanted)**
- [x] Publish it on NPM
- [x] Find a way to get smaller bundles when using ES6 modules
- [ ] Implement account handling (register, change passwords, etc)
- [x] ~~Implement passwords in folders~~ seems complicated

**Comment by qgustavor** [comment]
Following [webtorrent](https://github.com/feross/webtorrent/issues/653) the CLI will have it's own package.

**Comment by qgustavor** [comment]
Fixed issue as it's not being updated anymore. The missing features will only be implemented if someone requests those in other issue or if I find time to implement those.
